// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoDevopsClient is the client API for GoDevops service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoDevopsClient interface {
	UpdateMetric(ctx context.Context, in *MetricMessage, opts ...grpc.CallOption) (*UpdateMetricResponse, error)
}

type goDevopsClient struct {
	cc grpc.ClientConnInterface
}

func NewGoDevopsClient(cc grpc.ClientConnInterface) GoDevopsClient {
	return &goDevopsClient{cc}
}

func (c *goDevopsClient) UpdateMetric(ctx context.Context, in *MetricMessage, opts ...grpc.CallOption) (*UpdateMetricResponse, error) {
	out := new(UpdateMetricResponse)
	err := c.cc.Invoke(ctx, "/internal.rpc.proto.GoDevops/UpdateMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoDevopsServer is the server API for GoDevops service.
// All implementations must embed UnimplementedGoDevopsServer
// for forward compatibility
type GoDevopsServer interface {
	UpdateMetric(context.Context, *MetricMessage) (*UpdateMetricResponse, error)
	mustEmbedUnimplementedGoDevopsServer()
}

// UnimplementedGoDevopsServer must be embedded to have forward compatible implementations.
type UnimplementedGoDevopsServer struct {
}

func (UnimplementedGoDevopsServer) UpdateMetric(context.Context, *MetricMessage) (*UpdateMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetric not implemented")
}
func (UnimplementedGoDevopsServer) mustEmbedUnimplementedGoDevopsServer() {}

// UnsafeGoDevopsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoDevopsServer will
// result in compilation errors.
type UnsafeGoDevopsServer interface {
	mustEmbedUnimplementedGoDevopsServer()
}

func RegisterGoDevopsServer(s grpc.ServiceRegistrar, srv GoDevopsServer) {
	s.RegisterService(&GoDevops_ServiceDesc, srv)
}

func _GoDevops_UpdateMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoDevopsServer).UpdateMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.rpc.proto.GoDevops/UpdateMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoDevopsServer).UpdateMetric(ctx, req.(*MetricMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// GoDevops_ServiceDesc is the grpc.ServiceDesc for GoDevops service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoDevops_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.rpc.proto.GoDevops",
	HandlerType: (*GoDevopsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateMetric",
			Handler:    _GoDevops_UpdateMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
