# default.yml

server:
  address:
    host: 0.0.0.0
    port: 8080
  key: nil

agent:
  poll_interval: 1s
  report_interval: 10s
  client_timeout: 1s

store:
  database: null
  store_file: "/tmp/devops-metrics-db.json"
  restore: false
  store_interval: 300s